sonar.projectKey=viswavisan_applications
sonar.organization=viswavisan
sonar.host.url=https://sonarcloud.io
sonar.projectName=Applications Project
sonar.projectVersion=1.0
sonar.sources=.
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=Interview_evaluation/**,fit_mafia/test/**,fit_mafia/db.py,fit_mafia/models.py,fit_mafia/schemas.py,fit_mafia/__init__.py,fit_mafia/constants.py,fit_mafia/app.py,fit_mafia/object_storage.py,*.py,service/**,migrations/**
sonar.exclusions=**/__pycache__/**,**/*.pyc,venv/**,service/**,github/**
sonar.sourceEncoding=UTF-8
