sonar.projectKey=viswavisan_applications
sonar.organization=viswavisan
sonar.host.url=https://sonarcloud.io
sonar.projectName=Applications Project
sonar.projectVersion=1.0

# Sources
sonar.sources=.

# Coverage report (pytest generates coverage.xml)
sonar.python.coverage.reportPaths=coverage.xml

# Only check coverage for files in app/ and utils/
sonar.inclusions=**/app_controller.py

# Exclusions (optional)
sonar.exclusions=**/__pycache__/**,**/*.pyc,venv/**

# Encoding
sonar.sourceEncoding=UTF-8