sonar.projectKey=viswavisan_applications
sonar.organization=viswavisan
sonar.host.url=https://sonarcloud.io
sonar.projectName=Applications Project
sonar.projectVersion=1.0
sonar.sources=.
sonar.python.version=3.9
sonar.python.coverage.reportPaths=coverage.xml
sonar.tests=fit_mafia/test
sonar.coverage.exclusions=Interview_evaluation/**,fit_mafia/test/**,fit_mafia/db.py,fit_mafia/models.py,fit_mafia/schemas.py,fit_mafia/__init__.py,fit_mafia/constants.py,fit_mafia/app.py,*.py,service/**,migrations/**,fit_mafia/static/**
sonar.exclusions=**/__pycache__/**,**/*.pyc,venv/**,service/**,.github/workflows/**,fit_mafia/test/**
sonar.sourceEncoding=UTF-8
