"""Initial migration

Revision ID: 02c892d20824
Revises: 
Create Date: 2026-05-10 00:48:23.851288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c892d20824'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('session')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('end_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('session_id', name='session_pkey')
    )
    op.create_table('answers',
    sa.Column('applicant_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('applicant_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('questions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('applicant_id', name='answers_pkey')
    )
    # ### end Alembic commands ###
